package moncommerce.gestionFournisseur.service;

import moncommerce.gestionFournisseur.domain.model.FactureFournisseurReglementFournisseurs;
import moncommerce.gestionFournisseur.domain.model.FactureFournisseurReglementFournisseursPK;
import moncommerce.service.AbstractCrudService;

public interface FactureFournisseurReglementFournisseursService 
extends AbstractCrudService<FactureFournisseurReglementFournisseurs,FactureFournisseurReglementFournisseursPK> {
}
