package moncommerce.service;

import moncommerce.domain.model.FactureFournisseurReglementFournisseurs;
import moncommerce.domain.model.FactureFournisseurReglementFournisseursPK;

public interface FactureFournisseurReglementFournisseursService 
extends AbstractCrudService<FactureFournisseurReglementFournisseurs,FactureFournisseurReglementFournisseursPK> {
}
