package moncommerce.service.gestionFournisseur;

import moncommerce.domain.model.test.FactureFournisseurReglementFournisseurs;
import moncommerce.domain.model.test.FactureFournisseurReglementFournisseursPK;
import moncommerce.service.AbstractCrudService;

public interface FactureFournisseurReglementFournisseursService 
extends AbstractCrudService<FactureFournisseurReglementFournisseurs,FactureFournisseurReglementFournisseursPK> {
}
